language: cpp

git:
  quiet: true
  depth: 1

env:
  global:
    - COMMON_CMAKE_OPTIONS="-DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DCMAKE_INSTALL_PREFIX=install"

matrix:
  include:
    - name: "Ubuntu 16.04 - gcc-5.4 (Release) - ARM"
      os: linux
      arch: arm64
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Release"
        - CONAN_WEBREADY_DISABLED=1
        - COMMON_CMAKE_OPTIONS="-DEXIV2_ENABLE_WEBREADY=OFF -DEXIV2_ENABLE_CURL=OFF -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DCMAKE_INSTALL_PREFIX=install"

    - name: "Ubuntu 16.04 - gcc-5.4 (Release)"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Release"

    - name: "Ubuntu 16.04 - gcc-5.4 (Debug)"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Debug"

    - name: "Ubuntu 16.04 - gcc-5.4 with coverage"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - WITH_COVERAGE=1
        - BUILD_TYPE="Release"

    - name: "Ubuntu 16.04 - gcc-5.4 with Valgrind"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - WITH_VALGRIND=1
        - BUILD_TYPE="Release"

    - name: "Ubuntu 16.04 - gcc-5.4 with sanitizers"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - WITH_SANITIZERS=1
        - BUILD_TYPE="Release"

    - name: "Ubuntu 16.04 - CLANG 7.0 (Release)"
      os: linux
      dist: xenial
      sudo: required
      compiler: clang
      env:
        - BUILD_TYPE="Release"

    - name: "Ubuntu 16.04 - CLANG 7.0 (Debug)"
      os: linux
      dist: xenial
      sudo: required
      compiler: clang
      env:
        - BUILD_TYPE="Debug"

    - name: "macOS 10.14 - XCode 11.3"
      os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        - BUILD_TYPE="Release"

install: ./ci/install.sh
script:  ./ci/run.sh

cache:
    ccache: true
    directories:
    - conan         # Conan installation folder
    - $HOME/conanData     # Conan storage location
