image: Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

  PYTHON: "C:\\Python37"
    
  matrix:
      - SHARED: ON
      - SHARED: OFF

shallow_clone: true

install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - echo %APPVEYOR_BUILD_FOLDER%
    - if not exist deps mkdir deps
    - cd deps
    - if not exist ninja appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
    - if not exist ninja 7z x ninja.zip -o%APPVEYOR_BUILD_FOLDER%\deps\ninja > nul
    - set PATH=%APPVEYOR_BUILD_FOLDER%\deps\ninja;%PATH%
    - ninja --version
<<<<<<< HEAD
    - pip.exe install conan==1.19.1
=======
    - python -m pip install --upgrade pip
    - pip3.exe install conan==1.30.2
    - pip3.exe install lxml
>>>>>>> 3013f57e4... Use latest available version of Conan in CI
    - cd %APPVEYOR_BUILD_FOLDER%

before_build:
    - cmd: conan remote list
    - cmd: conan config set storage.path=c:\Users\appveyor\conanCache
    - cmd: conan profile new --detect default
    - cmd: conan profile update settings.compiler.version=15 default
    - cmd: if "%platform%"=="x64" (set ARCHITECTURE=x86_64) else (set ARCHITECTURE=x86)
    - cmd: if "%CONFIGURATION%"=="Debug" (set RUNTIME=MDd) else (set RUNTIME=MD)
    - cmd: conan profile update settings.arch=%ARCHITECTURE% default
    - cmd: conan profile update settings.arch_build=%ARCHITECTURE% default
    - cmd: conan profile update settings.build_type=%CONFIGURATION% default
    - cmd: conan profile update settings.compiler.runtime=%RUNTIME% default
    - cmd: cat c:\Users\appveyor\.conan\conan.conf
    - cmd: cat c:\Users\appveyor\.conan\profiles\default

build_script:
    - cmd: md build
    - cmd: cd build
    - cmd: if "%platform%"=="x64" (set VC_ARCH=x86_amd64) else (set VC_ARCH=x86)
    - cmd: call "%VCVARS%" %VC_ARCH%
    - cmd: conan install .. --build missing -o webready=True
    - cmd: cmake -GNinja -DBUILD_SHARED_LIBS=%SHARED% -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_WIN_UNICODE=ON -DCMAKE_INSTALL_PREFIX=install ..
    - cmd: ninja
    - cmd: ninja install
    - cmd: cd bin
    - cmd: unit_tests.exe
    - cmd: cd ../../tests/
    - cmd: set EXIV2_EXT=.exe
    - cmd: c:\Python36\python.exe runner.py -v

# We have disabled the cache system in master because for VS2017 we can find pre-compiled binaries
# for all the 3rd party dependencies in the conan-center bintray repository. The average time for
# each build in Appveyor is around 3 minutes which is not bad. If those times get worse over time
# we could think about re-enabling it.

#cache:
#- deps                          # Ninja installation
#- c:\Users\appveyor\conanCache  # Conan cache
