image: Visual Studio 2015

shallow_clone: true

install:
    - nuget install clcache
    - echo %APPVEYOR_BUILD_FOLDER%
    - mkdir C:\projects\deps
    - cd C:\projects\deps
    - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
    - 7z x ninja.zip -oC:\projects\deps\ninja > nul
    - set PATH=C:\projects\deps\ninja;%PATH%
    - ninja --version

before_build:
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: if not exist envs mkdir envs
    - cmd: cd envs
    - cmd: python -m virtualenv conan
    - cmd: conan/Scripts/activate
    - cmd: python -m pip install conan==1.6.1
    - cmd: cd ..
    - cmd: conan --version
    - cmd: conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - cmd: conan remote list
    - cmd: conan config set storage.path=c:\Users\appveyor\conanCache
    - cmd: cat c:\Users\appveyor\.conan\conan.conf
    - cmd: mkdir c:\Users\appveyor\.conan\profiles

build_script:
    - cmd: md build
    - cmd: cd build
    - cmd: conan install .. --build missing
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    - cmd: set CLCACHE_PATH=%APPVEYOR_BUILD_FOLDER%\clcache.4.1.0\clcache-4.1.0
    - cmd: set CLCACHE_DIR=%APPVEYOR_BUILD_FOLDER%\clcache.4.1.0\cache
    - cmd: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX=install ..
    - cmd: ninja
    - cmd: ..\clcache.4.1.0\clcache-4.1.0\clcache -s
    - cmd: ninja install
    - cmd: cd bin
    - cmd: unit_tests.exe
    - cmd: cd ../../tests/
    - cmd: set EXIV2_EXT=.exe
    - cmd: c:\Python36\python.exe runner.py -v

cache:
    - envs                          # Conan installation
    - clcache.4.1.0                 # clcache installation and cache
    - c:\Users\appveyor\conanCache  # Conan cache
